# Generated by Django 5.2.8 on 2025-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='code_of_conduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='country',
            field=models.CharField(blank=True, choices=[('Prefer not to answer', 'Prefer not to answer'), ('United States', 'United States'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany'), ('France', 'France'), ('Spain', 'Spain'), ('Italy', 'Italy'), ('China', 'China'), ('Japan', 'Japan'), ('India', 'India'), ('Australia', 'Australia'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='custom_allergy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='field_of_study',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Software Engineering', 'Software Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Information Systems', 'Information Systems'), ('Web Development', 'Web Development'), ('Game Development', 'Game Development'), ('Business', 'Business'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Psychology', 'Psychology'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AddField(
            model_name='attendee',
            name='field_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='food_allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendee',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Non-binary or Transgender', 'Non-binary or Transgender'), ('Other', 'Other'), ('Prefer not to answer', 'Prefer not to answer')], max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='level_of_study',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Post-Doctorate', 'Post-Doctorate'), ('Other', 'Other'), ("I'm not a student", "I'm not a student"), ('Prefer not to answer', 'Prefer not to answer')], max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='panther_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='attendee',
            name='photography_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Hispanic or Latine', 'Hispanic or Latine'), ('Black or African American', 'Black or African American'), ('Asian', 'Asian'), ('Native American or Alaskan Native', 'Native American or Alaskan Native'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('Middle Eastern', 'Middle Eastern'), ('Other', 'Other'), ('Prefer not to answer', 'Prefer not to answer')], max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='race_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='school_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5),
        ),
        migrations.AddField(
            model_name='attendee',
            name='state',
            field=models.CharField(blank=True, choices=[('Prefer not to answer', 'Prefer not to answer'), ('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='study_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='year_level',
            field=models.CharField(blank=True, choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Prefer not to answer', 'Prefer not to answer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='school',
            field=models.CharField(blank=True, choices=[('Florida International University', 'Florida International University'), ('University of Florida', 'University of Florida'), ('Florida State University', 'Florida State University'), ('University of Central Florida', 'University of Central Florida'), ('Florida Institute of Technology', 'Florida Institute of Technology'), ('Nova Southeastern University', 'Nova Southeastern University'), ('Florida Atlantic University', 'Florida Atlantic University'), ('University of South Florida', 'University of South Florida'), ('Florida A&M University', 'Florida A&M University'), ('Florida Polytechnic University', 'Florida Polytechnic University'), ('Harvard University', 'Harvard University'), ('MIT', 'MIT'), ('Stanford University', 'Stanford University'), ('UC Berkeley', 'UC Berkeley'), ('Georgia Tech', 'Georgia Tech'), ('Carnegie Mellon', 'Carnegie Mellon'), ('Other', 'Other')], max_length=255),
        ),
    ]
