# Generated by Django 5.2.6 on 2025-11-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_remove_attendee_food_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='resume_replacement_count',
            field=models.IntegerField(default=0, help_text='Number of times the resume has been replaced (max 2)'),
        ),
    ]

