# Generated by Django 5.2.6 on 2025-11-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_attendee_resume_replacement_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='resume_original_name',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded resume', max_length=255, null=True),
        ),
    ]

