# Generated by Django 5.2.8 on 2025-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_attendee_resume_original_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='panther_id',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='level_of_study',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Post-Doctorate', 'Post-Doctorate'), ('Faculty', 'Faculty'), ('Alumni', 'Alumni'), ('Other', 'Other'), ("I'm not a student", "I'm not a student"), ('Prefer not to answer', 'Prefer not to answer')], max_length=50),
        ),
    ]
